export const TOGGLE_LOAD = 'TOGGLE_LOAD';
export const TOGGLE_ERROR = 'TOGGLE_ERROR';
export const TOGGLE_DISABLE = 'TOGGLE_DISABLE';
export const UPDATE_FORM = 'UPDATE_FORM';
export const CHANGE_HOME_ROUTE = 'CHANGE_HOME_ROUTE';